CREATE DATABASE MEDICO_PACIENTE;
USE MEDICO_PACIENTE;

CREATE TABLE PESSOA(
    PES_INT_ID          INT             NOT NULL        IDENTITY(1,1),
    PES_STR_NOME        VARCHAR(70)     NOT NULL,
    PES_STR_NASCIMENTO  CHAR(8)         NOT NULL,
    PES_STR_CPF         CHAR(11)        NOT NULL,

	CONSTRAINT PK_PESSOA_ID	PRIMARY KEY(PES_INT_ID),
);

ALTER TABLE PESSOA
	ADD CONSTRAINT UK_PESSOA_CPF UNIQUE (PES_STR_CPF)

INSERT INTO PESSOA (PES_STR_NOME, PES_STR_NASCIMENTO, PES_STR_CPF)
VALUES ('Maria', '16021985', '15345623502'),
('Joaquim', '10021985', '15435689101'), 
('Monica', '01021975', '15431189101'),
('Armando', '10031905', '15431478911'),
('Angela', '10081915', '15435589101'),
('Kaique', '10061980', '15432038101'),
('Tania', '10101915', '15588689101'),
('Zaira', '10031984', '15632568101'),
('Jorge', '10071995', '15432788910'),
('Amanda', '10081915', '56932589101');

SELECT * FROM PESSOA;

CREATE TABLE MEDICO(
    MED_INT_ID          INT             NOT NULL        IDENTITY(1,1),
    MED_STR_CRM         CHAR(11)        NOT NULL,
	PES_INT_ID			INT				NOT NULL,

	CONSTRAINT	PK_MEDICO_ID	PRIMARY KEY(MED_INT_ID),
	CONSTRAINT UK_MEDICO_PESSOA_ID	UNIQUE (PES_INT_ID)
);

ALTER TABLE MEDICO
	ADD CONSTRAINT  UK_MEDICO_CRM	UNIQUE (MED_STR_CRM),
	CONSTRAINT FK_MEDICO_PESSOA_ID	
			FOREIGN KEY (PES_INT_ID)	
				REFERENCES	PESSOA(PES_INT_ID)

INSERT INTO MEDICO (MED_STR_CRM, PES_INT_ID) 
VALUES ('19995678911', 1);

INSERT INTO MEDICO (MED_STR_CRM, PES_INT_ID) 
VALUES('19997778911', 2),
('17530678911', 3),
('22395678910', 4);

CREATE VIEW VW_PESSOA_MEDICO AS
SELECT
P.PES_STR_NOME AS [Médico],
P.PES_STR_CPF  AS [CPF],
M.MED_STR_CRM  AS [CRM]
FROM PESSOA AS P INNER JOIN MEDICO AS M ON P.PES_INT_ID = M.PES_INT_ID

SELECT * FROM VW_PESSOA_MEDICO

CREATE TABLE PACIENTE(
    PAC_INT_ID          INT             NOT NULL        IDENTITY(1,1),
	PAC_STR_DESC		VARCHAR(70)		NOT NULL,
	PES_INT_ID			INT				NOT NULL,

	CONSTRAINT	PK_PACIENTE_ID	PRIMARY KEY (PAC_INT_ID),
	
	CONSTRAINT FK_PACIENTE_PESSOA_ID	FOREIGN KEY (PES_INT_ID)	REFERENCES	PESSOA(PES_INT_ID),
	CONSTRAINT UK_PACIENTE_PESSOA_ID	UNIQUE (PES_INT_ID)
);

INSERT INTO PACIENTE (PAC_STR_DESC, PES_INT_ID) 
VALUES ('Dor de cabeça', 1),
 ('Dor de cabeça', 2),
 ('Dor constante no abdomem', 3),
 ('Nauseas', 4),
 ('Febre constante', 5),
 ('Desmaios recorrentes', 6),
 ('Dengue', 7);

 SELECT * FROM PACIENTE;

CREATE VIEW VW_PESSOA_PACIENTE AS
SELECT
PESSOA.PES_INT_ID,
PESSOA.PES_STR_NOME,
PESSOA.PES_STR_CPF,
PESSOA.PES_STR_NASCIMENTO,
PACIENTE.PAC_STR_DESC
FROM PESSOA INNER JOIN PACIENTE ON PESSOA.PES_INT_ID = PACIENTE.PAC_INT_ID;

SELECT * FROM VW_PESSOA_PACIENTE;

CREATE TABLE CONSULTA(
    CON_INT_ID          INT             NOT NULL        IDENTITY(1,1),
	MED_INT_ID          INT             NOT NULL,
	PAC_INT_ID          INT             NOT NULL,

	CONSTRAINT	PK_CONSULTA_ID	PRIMARY KEY (CON_INT_ID),

	CONSTRAINT FK_CONSULTA_MEDICO_ID	FOREIGN KEY (MED_INT_ID)	REFERENCES	MEDICO(MED_INT_ID),
	CONSTRAINT FK_CONSULTA_PACIENTE_ID  FOREIGN KEY (PAC_INT_ID)	REFERENCES	PACIENTE(PAC_INT_ID)
);

CREATE VIEW VW_PACMED_CONSULTA AS
SELECT
    P1.PES_STR_NOME			AS NOME_MEDICO,
    MEDICO.MED_STR_CRM		AS CRM,
    P2.PES_STR_NOME			AS NOME_PACIENTE,
    PACIENTE.PAC_STR_DESC	AS SINTOMAS
FROM 
    MEDICO
INNER JOIN PESSOA AS P1 ON P1.PES_INT_ID		= MEDICO.MED_INT_ID
INNER JOIN PACIENTE		ON PACIENTE.PES_INT_ID	= P1.PES_INT_ID
INNER JOIN PESSOA AS P2 ON P2.PES_INT_ID		= PACIENTE.PES_INT_ID;

SELECT * FROM VW_PACMED_CONSULTA;

CREATE TABLE RECEITA(
    REC_INT_NUMERO          INT             NOT NULL,
    CON_INT_ID			INT				NOT NULL,
	REM_INT_ID			INT				NOT NULL,

	CONSTRAINT FK_RECEITA_CONSULTA_ID FOREIGN KEY (CON_INT_ID)	REFERENCES CONSULTA(CON_INT_ID)
);

CREATE TABLE REMEDIO(
    REM_INT_ID          INT             NOT NULL        IDENTITY(1,1),
    REM_STR_DESC		VARCHAR(60)		NOT NULL,
	REM_STR_CODBARRA	VARCHAR(45)		NOT NULL,

	CONSTRAINT	PK_REMEDIO_ID	PRIMARY KEY (REM_INT_ID),
);

ALTER TABLE RECEITA
	ADD CONSTRAINT FK_RECEITA_REMEDIO_ID FOREIGN KEY (REM_INT_ID)	REFERENCES REMEDIO(REM_INT_ID);